### ISSUE TITLE
kotlinのプロパティについて

### ISSUE THREAD

**Issue by kamedon** [mayahiro/DesignSupportTool#1]
はじめまして

Kotlinのパワフルな機能を使うともっと良くなると思いました。

!!はなるべく使わないようにしたほうがよいと思います。
!!は結局nullが来た時にヌルポインタが起きてしまいます。
Kotlinにはヌルポインタがおこなさないさまざまな便利機能がありますので
そちらでダメだった時の最終手段に使うと良いです。

OverlayShowService.ktで!!を使わない方法はいくつかあります。
紹介した方法の他にもたくさんありますが、
基本的なものだけ紹介します。

・ ?.を使う

Safe Calls
https://kotlinlang.org/docs/reference/null-safety.html

`wm!!.addView(view, params)`

を

`wm?.addView(view, params)`

にします
もしwmがNullだった場合は右側が実行されません
Javaでの等価コードは

`if(wm != null) wm.addView(view, params)`

・letを使う

nullじゃなかった時に何か実行したい時には
letがおすすめです。

let
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/let.html

java

```
if(wm != null){
処理(wm.addView(....))
hoge()
.....
}
```

```
wm?.let{
  it.addView(...)
 hoge()
}
```

itはwmを指しています。

・ lateinitを使う

Late-Initialized Properties
https://kotlinlang.org/docs/reference/properties.html

すべてで?.打つのは面倒なので、やっぱりvalで書けるなら書いたほうが楽です。
kotlinがAndroid向けに作ってくれたと思いますが
Android場合onCreate時に初期をすることが多いです
しかしval wm としてしまうと、コンストラクタの時に初期化しないといけなく
valで記述がする難しい時があります
そんなときにlateinitで初期化のタイミングを遅らせることができます。
ただし、lateinitは、値がセットさせる前に、参照させるとヌルポインタが発生します。

```
lateinit val wm : WindowManager

 override fun onCreate() {
        super.onCreate()
        wm = getSystemService(Context.WINDOW_SERVICE) as WindowManager
```

**Comment by kamedon** [comment]
すいません間違いがありました。
訂正させていただきます

lateinitも後から値が変わるのでvalではなくvarでないといけませんでした。

``` diff
- lateinit val wm : WindowManager
+ lateinit var wm : WindowManager

 override fun onCreate() {
        super.onCreate()
        wm = getSystemService(Context.WINDOW_SERVICE) as WindowManag
```

**Comment by mayahiro** [comment]
ご指摘ありがとうございます。
今回は「?.」を使う形で修正しました。
